# Generated by Django 3.1.2 on 2020-10-23 04:14

from django.db import migrations, models
import products.storates


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='media',
            field=models.FileField(blank=True, null=True, storage=products.storates.ProtectedStorage, upload_to='products/'),
        ),
    ]
